import time

from selenium import webdriver
from selenium.webdriver.support.select import Select


driver = webdriver.Chrome()

driver = webdriver.Chrome(r'C:/chromedriver/chromedriver.exe')
driver.set_window_size(1440,900)
driver.get("http://localhost/komp/")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul/li[4]/a').click()
time.sleep(3)

search_input = driver.find_element_by_xpath('/html/body/div[2]/form/input[1]')
search_input.send_keys('admin')
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/form/input[2]')
search_input.send_keys('admin')
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/form/input[3]').click()
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/form[1]/input').click()
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/div/a').click()
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/div/input')
driver.execute_script("window.scrollTo(0, 4000)")
search_input.send_keys('Zasilacze')
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/input').click()
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul/li[4]/a').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/form[2]/input').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/div/a').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/div[1]/input')
search_input.send_keys('Corsair')
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/div[2]/select/option[6]').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/input').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul/li[4]/a').click()
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/form[3]/input').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul/li[4]/a').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/form[4]/input').click()
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/div/a').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/div[1]/input')
time.sleep(3)
search_input.send_keys('test')
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/div[2]/input')
time.sleep(3)
search_input.send_keys('test')
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/input').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/table/tbody/tr[2]/td[3]/a[2]/span').click()
time.sleep(3)
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/div/div/div/form/div/p[2]/input').click()
driver.execute_script("window.scrollTo(0, 4000)")
time.sleep(3)

search_input = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul/li[4]/a').click()
time.sleep(3)
search_input = driver.find_element_by_xpath('/html/body/div[2]/form[5]/input').click()
time.sleep(3)
driver.quit()